My mobile first portofilo project consist of
misikira/Portofilo-Mobile-First pull request #1
Opened 2023-02-22 11:30 UTC by misikira

- Linter &hintrc to meet code standards 
- Gitignore to prevent unwanted config files for display
- Has a header
- Has a section to showcase project accomplished
- Got  a section to show my skills and my programming skills 
- Has a contact form and social media link to reach me
-

2023-02-22 15:53 UTC, tresorsawasawa requested changes
# STATUS: REQUIRED CHANGES :recycle::recycle: 

Hi @misikira 
Good job so far! I know you worked hard to implement this project, I really appreciate the effort you put in! But there are some issues that you still need to work on to go to the next project but you are almost there! 

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
- Follow GitHub flow :heavy_check_mark: 

## Required changes :recycle: :recycle: 
- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-22 15:53 UTC, tresorsawasawa commented on index.html
> +    </div>
- [ ] For best semantic tags, kindly ensure that the container of the section is a `section` tag and not a `div` tag. It represents a generic standalone section of the document,

2023-02-22 15:53 UTC, tresorsawasawa commented on index.html
> +        <hl class="name">misikir abate</hl>
- [ ] Kindly ensure that you use a `h1` tag on your main tittle for best semantics reasons

2023-02-22 15:53 UTC, tresorsawasawa commented on readme.md
> +
- [ ] I think it would be better if you fix the broken `[MIT](./LICENSE)` link in your README file to make it more professional as it shows a **404** error page once clicked. And to fix that, you can only create a new file name `LICENSE` in your root directory and get its content from this **[template](https://github.com/microverseinc/readme-template/blob/master/MIT.md)** or rename this `[MIT](./LICENSE)` to `[MIT](./MIT.md)`, then the created file in your directory name it `MIT.md` and use the same content in this **[template](https://github.com/microverseinc/readme-template/blob/master/MIT.md)**

2023-02-22 15:53 UTC, tresorsawasawa commented on index.html
> +    </div>
- [ ] Kindly make sure you stick as much as possible to your Figma template design. Tou add the background images, use correct fonts(size, weight,...),...

| Template Design | Your Design |
| --------------------- | ----------------- |
| ![Screenshot from 2023-02-22 17-41-38](https://user-images.githubusercontent.com/83042742/220677987-2700b20b-1791-43cf-803d-b989d501919c.png) | ![Screenshot from 2023-02-22 17-42-22](https://user-images.githubusercontent.com/83042742/220678103-b4988c84-4c22-4fdd-b87f-a31c7e150929.png) |

2023-02-22 15:53 UTC, tresorsawasawa commented on readme.md
> +
- [ **OPTIONAL** ] **RECOMMENDED:** I think it would be better if you fill all the sections with the correct contents to make your README professional

2023-02-23 10:06 UTC, misikira commented on index.html
> +        <hl class="name">misikir abate</hl>
> * [ ]  Kindly ensure that you use a `h1` tag on your main tittle for best semantics reasons

@tresorsawasawa sorry sir I am already  using h1 what I have to do I get your point

2023-02-23 11:04 UTC, brainconnect93 requested changes
## STATUS: Changes Required :recycle:

### Hi @misikira, 👋 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media.tenor.com/isiLRnxz3zwAAAAM/cat-driving-serious.gif" width="500px" height="300px">

### To Highlight :1st_place_medal: 
-  Has a proper Pull Request. ✔️  
- No Linter errors :heavy_check_mark: 
- Good use of Github flow ✔️ 

### Changes Required

- [x]  _Please check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @brainconnect93 ) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-23 11:04 UTC, brainconnect93 commented on index.html
> +    </section>
- [ ] As suggested by the previous reviewer, Kindly stick to the Figma design as much as possible. Below are highlights of some things I would suggest you work on to make your project looks perfect with what we have in the Figma design.

  - On class `..header-img2` kindly increase the left to `33rem`
  - On class `.about-me-detail` kindly make the width `75%`
  - On the button class `.colbrate-with-me` kindly make the width `90%` and replace the `margin-top` and `margin-bottom` with `margin: 2.4rem auto 3.2rem auto;`
  - Also kindly make the image below the `start collaboration` button a `background image` instead of making it an `img tag` in your HTML file. I would also advise you to check the image link as the image is currently broken

| Your Design  | Figma Design |
| ------------- | ------------- |
| ![abate](https://user-images.githubusercontent.com/78634841/220888587-dd20de81-c30c-44ca-b891-f542001a9596.png) | <img src="https://user-images.githubusercontent.com/83042742/220677987-2700b20b-1791-43cf-803d-b989d501919c.png"> |

2023-02-23 11:27 UTC, misikira commented on index.html
> +    </section>
> * [ ]  As suggested by the previous reviewer, Kindly stick to the Figma design as much as possible. Below are highlights of some things I would suggest you work on to make your project looks perfect with what we have in the Figma design.
>   
>   * On class `..header-img2` kindly increase the left to `33rem`
>   * On class `.about-me-detail` kindly make the width `75%`
>   * On the button class `.colbrate-with-me` kindly make the width `90%` and replace the `margin-top` and `margin-bottom` with `margin: 2.4rem auto 3.2rem auto;`
>   * Also kindly make the image below the `start collaboration` button a `background image` instead of making it an `img tag` in your HTML file. I would also advise you to check the image link as the image is currently broken
> 
> Your Design	Figma Design
> ![abate](https://user-images.githubusercontent.com/78634841/220888587-dd20de81-c30c-44ca-b891-f542001a9596.png)	![](https://user-images.githubusercontent.com/83042742/220677987-2700b20b-1791-43cf-803d-b989d501919c.png)

@brainconnect93 thank you for your feedback they are more than helpful and fixed everything as per your recommendation but can you clarify your last feedback mate that says  * Also kindly make the image below the `start collaboration` button a `background image` instead of making it an `img tag` in your HTML file. I would also advise you to check the image link as the image is currently broken

2023-02-23 12:40 UTC, misikira commented
thank you for your feedback they are more than helpful and fixed everything
as per your recommendation but can you clarify your last feedback mate that
says * Also kindly make the image below the start collaboration button
a background
image instead of making it an img tag in your HTML file. I would also
advise you to check the image link as the image is currently broken

On Thu, Feb 23, 2023 at 3:04 AM Afolabi Akorede ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
> STATUS: Changes Required ♻️ Hi @misikira <https://github.com/misikira>, 👋
>
> Good job so far!
> There are some issues that you still need to work on to go to the next
> project but you are almost there!
>
>
> <https://camo.githubusercontent.com/cf6e3cd7e4cbb865d88dd58069a57b1731d1a2ed019204f6cadf0414d954710e/68747470733a2f2f6d656469612e74656e6f722e636f6d2f6973694c526e787a337a77414141414d2f6361742d64726976696e672d736572696f75732e676966>
> To Highlight 🥇
>
>    - Has a proper Pull Request. ✔️
>    - No Linter errors ✔️
>    - Good use of Github flow ✔️
>
> Changes Required
>
>    - *Please check the comments under the review.*
>
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix won't stop the approval of this
> PR. However, I strongly recommend you to take them into account as they can
> make your code better. Some of them were simply missed by the previous
> reviewer and addressing them will really improve your application.*
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me on( @brainconnect93
> <https://github.com/brainconnect93> ) in your question so I can receive
> the notification.
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> In index.html
> <https://github.com/misikira/Portofilo-Mobile-First/pull/1#discussion_r1115500539>
> :
>
> >      <link rel="stylesheet" href="./style.css">
>
>  </head>
>
>  <body>
>
> -
>
> +    <header class="toolbar-header">
>
> +        <img src="./img/heade-side-img.svg" class="header-img1" alt="header logo image">
>
> +        <nav>
>
> +            <img src="./img/ic_menu.svg" class="header-img2" alt="mobile navigation menu ">
>
> +        </nav>
>
> +    </header>
>
> +    <section class="about-me">
>
> +        <hl class="name">misikir abate</hl>
>
> +        <h1> </h1>
>
>
>
>    - Kindly remove this empty h1 tag as it doesn't have any usefulness
>    again in your work.
>
> ------------------------------
>
> In index.html
> <https://github.com/misikira/Portofilo-Mobile-First/pull/1#discussion_r1115521807>
> :
>
> > +    <header class="toolbar-header">
>
> +        <img src="./img/heade-side-img.svg" class="header-img1" alt="header logo image">
>
> +        <nav>
>
> +            <img src="./img/ic_menu.svg" class="header-img2" alt="mobile navigation menu ">
>
> +        </nav>
>
> +    </header>
>
> +    <section class="about-me">
>
> +        <hl class="name">misikir abate</hl>
>
> +        <h1> </h1>
>
> +        <p class="about-me-detail">
>
> +            Hello! I am a software developer! I can help you build a product, feature or website. Take a look at my work.
>
> +            <br>
>
> +            &nbsp;
>
> +            &nbsp;
>
> +            &nbsp;
>
> +            <br>
>
> +            If you like what you see and have a project you need coded, don’t hesitate to contact me.
>
> +        </p>
>
> +        <button class="colbrate-with-me">Start collaboration</button>
>
> +        <img class="home-page-img1" src="./img/Thur.svg" alt="homepage image">
>
> +    </section>
>
>
>
>    -
>
>    As suggested by the previous reviewer, Kindly stick to the Figma
>    design as much as possible. Below are highlights of some things I would
>    suggest you work on to make your project looks perfect with what we have in
>    the Figma design.
>    - On class ..header-img2 kindly increase the left to 33rem
>       - On class .about-me-detail kindly make the width 75%
>       - On the button class .colbrate-with-me kindly make the width 90%
>       and replace the margin-top and margin-bottom with margin: 2.4rem
>       auto 3.2rem auto;
>       - Also kindly make the image below the start collaboration button a background
>       image instead of making it an img tag in your HTML file. I would
>       also advise you to check the image link as the image is currently broken
>
> Your Design Figma Design
> [image: abate]
> <https://user-images.githubusercontent.com/78634841/220888587-dd20de81-c30c-44ca-b891-f542001a9596.png>
> <https://user-images.githubusercontent.com/83042742/220677987-2700b20b-1791-43cf-803d-b989d501919c.png>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/misikira/Portofilo-Mobile-First/pull/1#pullrequestreview-1311006586>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AJ7Y7HGWFVJSA545F6P4E2DWY475JANCNFSM6AAAAAAVEGYEP4>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-02-23 14:07 UTC, misikira commented on index.html
> +    </section>
@brainconnect93 it says 284px why do I need to make it 33rem as you mention in the On class ..header-img2 kindly increase the left to 33rem help me out I am a bit confused. thank you.

2023-02-23 15:24 UTC, misikira commented
Will do, thanks!

On Thu, Feb 23, 2023 at 7:18 AM joel kalema ***@***.***>
wrote:

> ***@***.**** approved this pull request.
>
> Hi @misikira <https://github.com/misikira>
>
> Your project is complete! There is nothing else to say other than... it's
> time to merge it [image: :shipit:]
> Congratulations! 🎉
>
> <https://camo.githubusercontent.com/d8de195a08af080c4ae2fd36bfcf741de68f66af2162d291a21e113ce1b490fc/68747470733a2f2f6d65646961342e67697068792e636f6d2f6d656469612f42504a6d74685133595277443651716356442f67697068792e676966>
> Highlights
>
> Linters are passing 👍
> The project is running successfully 👍
> PR is well descriptive 👍
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix won't stop the approval of this
> PR. However, I strongly recommend you to take them into account as they can
> make your code better. Some of them were simply missed by the previous
> reviewer and addressing them will really improve your application.*
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me ***@***.*** <https://github.com/joel-kalema>*
> in your question so I can receive the notification.
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/misikira/Portofilo-Mobile-First/pull/1#pullrequestreview-1311532475>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AJ7Y7HB5SUMDSYTD36SMML3WY55S7ANCNFSM6AAAAAAVEGYEP4>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-02-23 19:06 UTC, merged