Contact form
misikira/Portofilo-Mobile-First pull request #7
Opened 2023-03-02 12:44 UTC by misikira

1. has a name input field
2. has email input
3. has the facility to send message 
4. data validation as per project requirement

2023-03-02 12:58 UTC, misikira commented
![microverse](https://user-images.githubusercontent.com/41914268/222435069-90aac408-7153-4fa7-977d-b2f626c2d22f.PNG)

2023-03-02 13:00 UTC, amejid reviewed
Hi @misikira, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not have a README file.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-03-02 16:01 UTC, AbayomiOlaoye requested changes
## STATUS: CHANGE REQUIRED ♻️ 

Hi @misikira :wave: , 

Good job with this milestone so far!
There are just a few more issues to work on before moving on to the next project but you are almost there!

![so_close](https://user-images.githubusercontent.com/99715640/211950260-0e3881c0-9d4f-4ea2-a670-9ef45a23a0f5.gif)

## Highlights
- Descriptive Pull Request message :heavy_check_mark: 
- Good use of GitHub flow :heavy_check_mark: 
- Meaningful commit messages :heavy_check_mark: 
- No linter error :heavy_check_mark: 
- Descriptive ReadMe documentation :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-03 07:59 UTC, merged

2023-03-03 08:22 UTC, misikira commented
oh my god I accidentally closed and merged my intention was to merge the animation branch which doesn't need reviewer feedback I am working to resolve this

2023-03-03 14:47 UTC, Abenezer-Tilahun reviewed
Hi @misikira  , 

Great job for implemented  the suggested changes by the previous reviewer , but there are some changes that need to be implemented in order to proceed to the next project 👍

## Highlights 👏🏻

✔️ No Linters error
✔️ You used correct Git Hub-Flow.
✔️ Good Commit Messages
✔️ Professional READEME 


![almost](https://user-images.githubusercontent.com/65860678/170491251-b1add8ba-b18f-4648-a893-20e510d957fd.gif)

## Required Changes ♻️
_Check the comments below the review._

- [x] For Your future project kindly make sure that before you got approved for this project activity kindly i recommend you not to merge to main branch.  

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-03 14:47 UTC, Abenezer-Tilahun commented on index.html
> +                             label="Your name" maxlength="15" name="name" >
- [ ] As stated in the project requirement Kindly make sure that **Name field accepts up to 30 chars.** and **A user cannot submit the form if one or more of the fields is empty.** So Kindly make `maxlength="30"` and add `required` attribute to the name field.

2023-03-03 14:47 UTC, Abenezer-Tilahun commented on index.html
> +                            class="form-input" label="Your email" name="email" name="your message">
- [ ] As stated in the project requirement Kindly make sure that **A user cannot submit the form if one or more of the fields is empty**. So Kindly make  add `required` attribute to the email field.

2023-03-03 15:23 UTC, misikira commented on index.html
> +                            class="form-input" label="Your email" name="email" name="your message">
@Abenezer-Tilahun  thank you for your helpful recommendations and fixed the issues as per your review the problem I am having is I accidentally merged and closed my branch if I push from this branch will it create a new pull request how can I resolve this

2023-03-03 17:01 UTC, Abenezer-Tilahun commented on index.html
> +                            class="form-input" label="Your email" name="email" name="your message">
Hello @misikira I see that so implemented all the change and submit with new pull request and on the pull request description  please refer this pull request for the next reviewer reference.

2023-03-03 17:09 UTC, misikira commented on index.html
> +                            class="form-input" label="Your email" name="email" name="your message">
Thanks for reaching me out I just did that got approved

2023-03-03 19:12 UTC, misikira commented on index.html
> +                            class="form-input" label="Your email" name="email" name="your message">
@Abenezer-Tilahun  Thanks for reaching me I just did that and got approved